# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idpzero < Formula
  desc "Single binary Identity Provider (IDP) for local dev/test"
  homepage "https://idpzero.dev"
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/idpzero/idpzero/releases/download/v0.1.3/idpzero_Darwin_x86_64.tar.gz"
      sha256 "664e618cac05b03159cb90805565b7c4a440e6182583c883362a0007d87acbc0"

      def install
        bin.install "idpzero"
      end
    end
    on_arm do
      url "https://github.com/idpzero/idpzero/releases/download/v0.1.3/idpzero_Darwin_arm64.tar.gz"
      sha256 "f3dd477f7d39d714367a0a74f1645e593a14d73d6b3733e67779a2d47d02e345"

      def install
        bin.install "idpzero"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/idpzero/idpzero/releases/download/v0.1.3/idpzero_Linux_x86_64.tar.gz"
        sha256 "40cace6837e8138641147910e3a21a8f6fba0352b5a1d34ad273a18567f30917"

        def install
          bin.install "idpzero"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/idpzero/idpzero/releases/download/v0.1.3/idpzero_Linux_arm64.tar.gz"
        sha256 "8e0fb66e8198fbd6863af53ffa3e8ae5257a596ba47c7aaee6de3416893fa6a2"

        def install
          bin.install "idpzero"
        end
      end
    end
  end
end
