# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idpzero < Formula
  desc "Single binary Identity Provider (IDP) for local dev/test"
  homepage "https://idpzero.dev"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/idpzero/idpzero/releases/download/v0.1.0/idpzero_Darwin_x86_64.tar.gz"
      sha256 "22ecb36644e38de31cc2695acf3b751e6765ae7a28d86c60095b4b0c7ea1c6c4"

      def install
        bin.install "idpzero"
      end
    end
    on_arm do
      url "https://github.com/idpzero/idpzero/releases/download/v0.1.0/idpzero_Darwin_arm64.tar.gz"
      sha256 "dbad3feaf913aacc730633d8572bed14d5f2fd9ba5d49e619d90c84e7ea7dd9f"

      def install
        bin.install "idpzero"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/idpzero/idpzero/releases/download/v0.1.0/idpzero_Linux_x86_64.tar.gz"
        sha256 "e348f2117a37ef2d7f1cc24d9f7d0b8b38a2ff72c61dd6e53c9035d8925abe1b"

        def install
          bin.install "idpzero"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/idpzero/idpzero/releases/download/v0.1.0/idpzero_Linux_arm64.tar.gz"
        sha256 "ff0765d9cac6af632306f71bdefde7cf347d0111bb4f70a1330bba4cc58f9a2c"

        def install
          bin.install "idpzero"
        end
      end
    end
  end
end
